#!/bin/bash
# ============================================================
# 🌌 Etherverse Self-Optimize Module
# ============================================================

BASE_DIR="$HOME/etherverse"
LOG_DIR="$BASE_DIR/logs"
REPORT_DIR="$BASE_DIR/docs"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="$REPORT_DIR/self_optimize_${TIMESTAMP}.md"

mkdir -p "$LOG_DIR" "$REPORT_DIR"

echo "[$(date)] 🚀 Starting Self-Optimization" | tee -a "$LOG_DIR/self_optimize.log"

# 1️⃣ Run diagnostics
if [ -f "$BASE_DIR/scripts/quantum_diagnostics.sh" ]; then
  bash "$BASE_DIR/scripts/quantum_diagnostics.sh" | tee -a "$LOG_DIR/self_optimize.log"
else
  echo "[⚠️] Diagnostics script missing." | tee -a "$LOG_DIR/self_optimize.log"
fi

# 2️⃣ Fix empty or missing core schemas
for f in core/identity_schema.json core/memory_protocol.md core/api_manifest.json; do
  if [ ! -s "$BASE_DIR/$f" ]; then
    echo "[🧩] Rebuilding $f ..." | tee -a "$LOG_DIR/self_optimize.log"
    mkdir -p "$(dirname "$BASE_DIR/$f")"
    cat > "$BASE_DIR/$f" <<EOF
{
  "version": "1.0",
  "generated": "$(date)",
  "description": "Autogenerated placeholder. Define detailed schema here."
}
EOF
  fi
done

# 3️⃣ Dependency and environment sync
source "$BASE_DIR/venv/bin/activate"
pip install -U --quiet --no-cache-dir pip setuptools wheel
pip install --upgrade --quiet --no-cache-dir deptry || echo "[ℹ️] deptry unavailable"
pip check || echo "[ℹ️] Dependency check complete."

# 4️⃣ Git auto-sync (safe)
cd "$BASE_DIR"
git add -A
git commit -m "🤖 Auto-Optimize: dependency sync, schema regen, diagnostics $(date)" 2>/dev/null
git push origin main 2>/dev/null || echo "[⚠️] Git push skipped (offline or token protected)."

echo -e "\n[✅] Self-Optimization complete. Logged to $LOG_DIR/self_optimize.log"
